import manifest from '@/asset-audit/market-2026-09-14/frames.json';
import terrainManifest from '@/asset-audit/market-terrain-2026-09-20/frames.json';
import {
  HOME_GROUND,
  HOME_SHEET_KEYS,
  homeFrame,
  homeFrameName,
} from '@/game/config/homeAssets';
import type { CollisionRect } from '@/game/types';

// Market's own sheets. Source rectangles come from
// `asset-audit/market-2026-09-14/frames.json`, generated by the same alpha-mask
// component analysis used for Home; nothing here is a hand-typed crop.
const SHEETS = manifest.sheets as unknown as readonly {
  key: string;
  url: string;
  width: number;
  height: number;
  frames: Record<string, CollisionRect | undefined>;
}[];

export const MARKET_SHEET_KEYS = {
  projshop: 'market-projshop',
  storage: 'market-storage',
  furniture: 'market-furniture',
  signage: 'market-signage',
} as const;
export type MarketSheet =
  (typeof MARKET_SHEET_KEYS)[keyof typeof MARKET_SHEET_KEYS];

/** The name-entry sheet is a React/CSS asset, not a Phaser texture. */
export const NAME_ENTRY_SHEET = 'name-entry-ui';

export const MARKET_TEXTURES: readonly { key: MarketSheet; url: string }[] =
  Object.values(MARKET_SHEET_KEYS).map((key) => {
    const sheet = SHEETS.find((entry) => entry.key === key);
    if (!sheet) throw new Error(`Market sheet is not audited: ${key}`);
    return { key, url: sheet.url };
  });

export function marketFrame(sheet: string, name: string): CollisionRect {
  const entry = SHEETS.find((candidate) => candidate.key === sheet);
  if (!entry) throw new Error(`Market sheet is not audited: ${sheet}`);
  const frame = entry.frames[name];
  if (!frame) throw new Error(`Unaudited market frame: ${sheet}.${name}`);
  return frame;
}

export function marketFrameName(sheet: string, name: string) {
  return `${sheet}.${name}`;
}

/** CSS `background-position`/`size` for one frame of a sheet, for React UI. */
export function frameAsCss(sheet: string, name: string, url: string) {
  const entry = SHEETS.find((candidate) => candidate.key === sheet);
  if (!entry) throw new Error(`Sheet is not audited: ${sheet}`);
  const frame = entry.frames[name];
  if (!frame) throw new Error(`Unaudited frame: ${sheet}.${name}`);
  return { url, frame, sheetWidth: entry.width, sheetHeight: entry.height };
}

/**
 * Shows exactly one frame stretched to fill a responsive box. Percentage
 * background-position resolves against (box - image), so the offset that puts
 * the frame's own origin at 0 is `fx / (sheetWidth - frameWidth)`.
 */
export function frameBackgroundStyle(sheet: string, name: string, url: string) {
  const { frame, sheetWidth, sheetHeight } = frameAsCss(sheet, name, url);
  return {
    backgroundImage: `url('${url}')`,
    backgroundSize: `${(sheetWidth / frame.width) * 100}% ${(sheetHeight / frame.height) * 100}%`,
    backgroundPosition: `${(frame.x / (sheetWidth - frame.width)) * 100}% ${(frame.y / (sheetHeight - frame.height)) * 100}%`,
    backgroundRepeat: 'no-repeat' as const,
    aspectRatio: `${frame.width} / ${frame.height}`,
  };
}

// The market floor is the Guild exterior's terrain sheet. That sheet is opaque,
// so `asset-audit/market-terrain-2026-09-20` segments it against its gutter
// colour and shrinks every frame to the largest gutter-free rect; nothing below
// is a hand-typed crop and no frame can paint the sheet's backdrop.
const TERRAIN_SHEET = terrainManifest.sheets[0] as unknown as {
  key: string;
  url: string;
  frames: Record<string, CollisionRect | undefined>;
};

export const MARKET_TERRAIN_TEXTURE = {
  key: TERRAIN_SHEET.key,
  url: TERRAIN_SHEET.url,
} as const;

export function terrainFrame(name: string): CollisionRect {
  const frame = TERRAIN_SHEET.frames[name];
  if (!frame) throw new Error(`Unaudited terrain frame: ${name}`);
  return frame;
}

export function terrainFrameName(name: string) {
  return `${MARKET_TERRAIN_TEXTURE.key}.${name}`;
}

// Ground, road and boundary planting are shared with Home. Market reuses Home's
// audited lookups rather than re-auditing the same three sheets.
export {
  HOME_GROUND as MARKET_GROUND,
  HOME_SHEET_KEYS as SHARED_SHEET_KEYS,
  homeFrame as sharedFrame,
  homeFrameName as sharedFrameName,
};
